name: Release Delivery
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Archive site content
      uses: thedoctor0/zip-release@master
      with:
        filename: content.zip
    - name: Set environment variables for version number
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Echo Version Tag
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }} 
    - name: Send Email
      uses: dawidd6/action-send-mail@v3.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Team 5 SimpCity Release ${{ env.RELEASE_VERSION }}
        # Required recipients' addresses:
        to:  ict.devops.consultants@gmail.com
        # Required sender full name (address can be skipped):
        from: Team 5 SimpCity
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: | 
          There is an updated release ${{ env.RELEASE_VERSION }} for SimpCity! (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
          Release link: https://github.com/${{ github.repository }}/releases/tag/${{ env.RELEASE_VERSION }}
        # Carbon copy recipients (separated with comma)
        cc: s10196822@connect.np.edu.sg
        # Optional attachments:
        attachments: content.zip
