name: get commit message

on: 
  push:
    branches: [main]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
        
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: huanhuiying/DevOps_Oct2021_Team-5
    
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/942459318530347029/jZqa1-I1KjRlR4c-wpIqJAVC0QExur6JxJTeQHOq-QLRFGG2RCW1Vt5lP6rjxcycOJcu
      uses: Ilshidur/action-discord@master
      with:
       args: '${{ github.event.head_commit.message }}'
