name: CI pull request for SimpCity

on: 
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
        
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: huanhuiying/DevOps_Oct2021_Team-5
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repository: huanhuiying/DevOps_Oct2021_Team-5
        path: tests
        
    - name: Begin Pytest
      run: |
        mv ./tests/*.* ./
        pytest --cov -v --junitxml=report.xml
    - if: ${{failure()}}       
      name: Create Issues
      uses: nashmaniac/create-issue-action@v1.1
      with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}} @ ${{github.ref}}       

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.24
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: report.xml
  
    - name: Notify discord
      uses: th0th/notify-discord@v0.4.1
      if: ${{ always() }}
      env:
        DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/941988093379104770/fxpl-UsFAAWYG4pS54WnKlVJAUdfynXAbvuksQrr9YOMhIa4r_t39PaciGF7qbzt1qBM
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_JOB_NAME: "Unit Test Status"
        GITHUB_JOB_STATUS: ${{ job.status }}
